BUILDSCAD_PROJECT=spacer-blocks
BUILDSCAD_VERSION=1.0.0
BUILDSCAD_AUTHOR=dduxx
BUILDSCAD_ASSEMBLIES=scad/assemblies/imperial.scad,\
    scad/assemblies/metric.scad
BUILDSCAD_LOG_LEVEL=INFO
BUILDSCAD_OPENSCAD_PATH=openscad-nightly
BUILDSCAD_OUTPUT_FORMAT=stl,3mf,png
BUILDSCAD_OPENSCAD_COLORSCHEME=DeepOcean
